name: circlesquarearchitects.com/contacts
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.48733978369273245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4e2f8'
    - '#6e6c6d'
    - '#0c2223'
    - '#ff0020'
    - '#0095fb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
